### ISSUE TITLE
Error Page could not Load

### ISSUE THREAD

**Issue by luzpaz** [scribusproject/scribus-tutorials#4]
@OceanWolf I'm trying to run the gh-pages branch locally and I get the above error.
file:///Users/test/Develop/scribus-tutorials/index.html#undefined

Any fix for this ?

**Comment by OceanWolf** [comment]
Um, not sure where that error comes from (I would need to see a screenshot or something).

When I first started creating it I did it "locally" and the ajax didn't work in firefox... as a webdeveloper I have apache installed so I just added an extra virtual host, and then the ajax worked... probably just a firefox bug/intentional-behaviour.

I can look into it, and come up with a workaround if necessary... (i.e. in the js detect if running from server use ajax, otherwise open file from filesystem).

P.S. now you see it online, what do you think?

**Comment by luzpaz** [comment]
It works 100% online so far.

**Comment by OceanWolf** [comment]
Shall I close this, or do you think it important that we can run it locally without installing apache or some other webserver?

**Comment by luzpaz** [comment]
no..not high priority. But we should notate it somwhere that a webserver is needed to run it locally. 
Closing
