### ISSUE TITLE
Feature: contents file to be autogenerated ?

### ISSUE THREAD

**Issue by luzpaz** [scribusproject/scribus-tutorials#6]
Perhaps instead of manually adding tutorials names to `contents` file, could we have some .js code search the gh-pages branch for .md file names and auto-generate the contents sidebar ?

Is that useful?

**Comment by luzpaz** [comment]
and bake in the possibility to exclude certain .md files ie. README.md

**Comment by OceanWolf** [comment]
I don't think so... because we can have a predefined order in the `contents` file.  Also we have much finer control, omitting pages etcetera with a contents file.

See my upgraded v0.8 engine in #11 with the format:

```
[url.md] [The Title]
```

with the url not allowing spaces, basically here the url functions as the page number of a traditional contents, followed by a (short) description.  This approach gives us far more flexibility by separating these two different aspects from one another.

**Comment by OceanWolf** [comment]
P.S.  Sorry for the late reply, I didn't know you had written anything to me until I just noticed the high issue count... you should have poked me, either with an @ mention, or on one of the other channels ;).

**Comment by luzpaz** [comment]
Yea..closing. You're idea makes more sense

**Comment by OceanWolf** [comment]
Freenode not working for me any more :(
